version: '2.2'
services:

  nginx:
    container_name: guestbook_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./images/nginx/guestbook.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
      - ./logs:/var/log/nginx
    networks:
      - guestbook-net
  
  phpfpm:
    container_name: guestbook_phpfpm
    ports:
      - "8080:8080"
    build: ./images/phpfpm
    volumes:
      - ./app:/var/www
    networks:
      - guestbook-net

  db:
    image: postgres
    container_name: guestbook_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=guestbook
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - guestbook-net


networks:
  guestbook-net:
    driver: bridge


